# Generated by Django 6.1.1 on 2026-10-03 09:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Developer", "Developer"),
                            ("Data Analyst", "Data Analyst"),
                            ("Data Engineer", "Data Engineer"),
                            ("BI Developer", "BI Developer"),
                            ("Tech Lead", "Tech Lead"),
                            ("Business Analyst", "Business Analyst"),
                            ("QA Engineer", "QA Engineer"),
                            ("Technical Consultant", "Technical Consultant"),
                            ("Project Manager", "Project Manager"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "allocation_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("allocation_start_date", models.DateField()),
                ("allocation_end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_allocations",
                        to="employees.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_allocations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "project"), name="unique_employee_project"
                    )
                ],
            },
        ),
    ]
